version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=partycrawler
      - POSTGRES_PASSWORD=partycrawler
      - POSTGRES_DB=partycrawler
      - TZ=utc