version: '3.1'

services:
  db:
    container_name: 'partycrawler_db'
    image: postgres:latest
    environment:
      - POSTGRES_USER=partycrawler
      - POSTGRES_PASSWORD=partycrawler
      - POSTGRES_DB=partycrawler
      - TZ=utc
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 35432:5432
volumes:
  postgres_volume:
