version: '3.1'

services:
  db:
    container_name: 'partycrawler_db'
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=partycrawler
      - POSTGRES_PASSWORD=partycrawler
      - POSTGRES_DB=partycrawler
      - TZ=utc
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 35432:5432
  minio:
    container_name: 'partycrawler_minio'
    image: minio/minio
    restart: always
    ports:
      - 39000:9000
    command:
      - server
      - /data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - minio_volume:/data
volumes:
  postgres_volume:
  minio_volume:
